# Generated by Django 5.1.5 on 2025-05-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karelapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hracikarel',
        ),
        migrations.DeleteModel(
            name='karel_zakladni_staty',
        ),
    ]
