# Generated by Django 5.1.5 on 2025-06-17 15:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0007_remove_pamet_pepa_zustatek_na_ucte'),
        ('karelapp', '0002_delete_hracikarel_delete_karel_zakladni_staty'),
    ]

    operations = [
        migrations.CreateModel(
            name='karel_inv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('den', models.IntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('vaha_inventare', models.FloatField(default=1)),
                ('objem_inventare', models.FloatField(default=1)),
                ('cena_inv', models.FloatField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Karel INV',
                'verbose_name_plural': 'Karel INV',
            },
        ),
        migrations.CreateModel(
            name='karel_snedl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('den', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('snedeno_kcal', models.FloatField(blank=True, default=0)),
                ('snedeno_sytost', models.FloatField(blank=True, default=0)),
                ('snedeno_hydratace', models.FloatField(blank=True, default=0)),
                ('snedeno_hmotnost', models.FloatField(blank=True, default=0)),
                ('snedeno_energie', models.FloatField(blank=True, default=0, max_length=1000)),
            ],
            options={
                'verbose_name': 'Co Karel snědl',
                'verbose_name_plural': 'Co Karel snědl',
            },
        ),
        migrations.CreateModel(
            name='karel_zakladni_staty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=10)),
                ('vek', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('vyska', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('vaha', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('pohlavi', models.CharField(max_length=10)),
                ('delkakroku', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'KAREL - Základní staty',
                'verbose_name_plural': 'KAREL - Základní staty',
            },
        ),
        migrations.CreateModel(
            name='karel_equip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('den', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('equip_pozn', models.CharField(blank=True, max_length=1000, null=True)),
                ('equip_zatez', models.FloatField(blank=True, default=0, null=True)),
                ('equip_objem', models.FloatField(blank=True, default=0, null=True)),
                ('equip_cena', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_delka_kroku_procenta', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_BMR_procenta', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_zatez_procenta', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_income_flat', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_income_procenta', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_kapacita_flet', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_kapacita_procenta', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_XP_flat', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_XP_procenta', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_spanek_flat', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_spanek_procenta', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_cena_procenta', models.FloatField(blank=True, default=0)),
                ('equip_batoh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karel_equip_batoh', to='adminapp.vybava')),
                ('equip_boty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karel_equip_boty', to='adminapp.vybava')),
                ('equip_doplnek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karel_equip_doplnek', to='adminapp.vybava')),
                ('equip_kalhoty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karel_equip_kalhoty', to='adminapp.vybava')),
                ('equip_karimatka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karel_equip_karimatka', to='adminapp.vybava')),
                ('equip_ponozky', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karel_equip_ponozky', to='adminapp.vybava')),
                ('equip_spacak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karel_equip_spacak', to='adminapp.vybava')),
                ('equip_triko', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karel_equip_triko', to='adminapp.vybava')),
            ],
            options={
                'verbose_name': 'Co má Karel na sobě',
                'verbose_name_plural': 'Co má Karel na sobě',
            },
        ),
        migrations.CreateModel(
            name='InventarPolozkaVybava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnozstvi', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('polozka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karel_inventar_vybava', to='adminapp.vybava')),
                ('inventar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vybaveni', to='karelapp.karel_inv')),
            ],
        ),
        migrations.CreateModel(
            name='InventarPolozkaFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnozstvi', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('polozka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karel_inventar_food', to='adminapp.food_drink')),
                ('inventar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potraviny', to='karelapp.karel_inv')),
            ],
        ),
        migrations.CreateModel(
            name='karel_snedl_polozka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('den', models.IntegerField(blank=True, default=1)),
                ('mnozstvi', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('snedeno_kcal', models.FloatField(blank=True, default=0)),
                ('snedeno_sytost', models.FloatField(blank=True, default=0)),
                ('snedeno_hydratace', models.FloatField(blank=True, default=0)),
                ('snedeno_hmotnost', models.FloatField(blank=True, default=0)),
                ('snedeno_energie', models.FloatField(blank=True, default=0, max_length=1000)),
                ('jidlo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karel_snedl_polozka', to='adminapp.food_drink')),
                ('karel_snedl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polozky', to='karelapp.karel_snedl')),
            ],
        ),
    ]
