# Generated by Django 5.1.5 on 2025-07-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karelapp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karel_equip',
            name='equip_pozn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
