# Generated by Django 5.1.5 on 2025-07-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karelapp', '0005_alter_karel_equip_equip_pozn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karel_zakladni_staty',
            name='delkakroku',
            field=models.FloatField(default=0, max_length=50),
        ),
    ]
