# Generated by Django 5.1.5 on 2025-07-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karelapp', '0007_alter_karel_zakladni_staty_delkakroku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karel_zakladni_staty',
            name='pohlavi',
            field=models.CharField(max_length=100),
        ),
    ]
