# Generated by Django 5.1.5 on 2025-07-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karelapp', '0008_alter_karel_zakladni_staty_pohlavi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karel_zakladni_staty',
            name='pohlavi',
            field=models.CharField(max_length=10),
        ),
    ]
