# Generated by Django 5.1.5 on 2025-07-18 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karelapp', '0009_alter_karel_zakladni_staty_pohlavi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karel_equip',
            name='equip_pozn',
        ),
    ]
