# Generated by Django 5.1.5 on 2025-07-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karelapp', '0010_remove_karel_equip_equip_pozn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karel_equip',
            name='equip_BONUS_cena_procenta',
            field=models.FloatField(blank=True, default=0, max_length=100),
        ),
    ]
