# Generated by Django 5.1.5 on 2025-05-31 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infopage', '0002_alter_vysledky_hracu_prijmeni'),
    ]

    operations = [
        migrations.AddField(
            model_name='vysledky_hracu',
            name='koeficient',
            field=models.FloatField(blank=True, default=1, max_length=10, null=True),
        ),
    ]
