# Generated by Django 5.1.5 on 2025-05-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infopage', '0003_vysledky_hracu_koeficient'),
    ]

    operations = [
        migrations.AddField(
            model_name='vysledky_hracu',
            name='pozn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
