# Generated by Django 5.1.5 on 2025-05-31 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infopage', '0004_vysledky_hracu_pozn'),
    ]

    operations = [
        migrations.AddField(
            model_name='vysledky_hracu',
            name='max_kroku_mesicne',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)]),
        ),
        migrations.AlterField(
            model_name='vysledky_hracu',
            name='koeficient',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
