# Generated by Django 5.1.5 on 2025-05-31 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infopage', '0005_vysledky_hracu_max_kroku_mesicne_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vysledky_hracu',
            name='pozn',
        ),
    ]
