# Generated by Django 5.1.5 on 2025-06-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infopage', '0006_remove_vysledky_hracu_pozn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vysledky_hracu',
            name='prijmeni',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
