# Generated by Django 5.1.5 on 2025-05-26 07:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hracipepa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=20)),
                ('prijmeni', models.CharField(max_length=30)),
                ('tym', models.CharField(max_length=10, null=True)),
                ('kroky_BONUS', models.IntegerField(blank=True, default=0)),
                ('kroky1', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)])),
                ('kroky2', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)])),
                ('kroky3', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)])),
                ('kroky4', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)])),
                ('kroky5', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)])),
                ('kroky6', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)])),
                ('kroky7', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)])),
                ('kroky8', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)])),
                ('kroky9', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)])),
                ('kroky10', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)])),
                ('kroky11', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)])),
                ('kroky12', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)])),
                ('celkem_kroku', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
            ],
            options={
                'verbose_name': 'PEPA - Výsledky hráčů',
                'verbose_name_plural': 'PEPA - Výsledky hráčů',
            },
        ),
        migrations.CreateModel(
            name='pepa_inv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('den', models.IntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('vaha_inventare', models.FloatField(default=1)),
                ('objem_inventare', models.FloatField(default=1)),
                ('cena_inv', models.FloatField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Pepa INV',
                'verbose_name_plural': 'Pepa INV',
            },
        ),
        migrations.CreateModel(
            name='pepa_snedl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('den', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('snedeno_kcal', models.FloatField(blank=True, default=0)),
                ('snedeno_sytost', models.FloatField(blank=True, default=0)),
                ('snedeno_hydratace', models.FloatField(blank=True, default=0)),
                ('snedeno_hmotnost', models.FloatField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Co Pepa snědl',
                'verbose_name_plural': 'Co Pepa snědl',
            },
        ),
        migrations.CreateModel(
            name='pepa_zakladni_staty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=10)),
                ('vek', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('vyska', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('vaha', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('pohlavi', models.CharField(max_length=10)),
                ('delkakroku', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'PEPA - Základní staty',
                'verbose_name_plural': 'PEPA - Základní staty',
            },
        ),
        migrations.CreateModel(
            name='pepa_equip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('den', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('equip_pozn', models.CharField(blank=True, max_length=1000, null=True)),
                ('equip_zatez', models.FloatField(blank=True, default=0, null=True)),
                ('equip_objem', models.FloatField(blank=True, default=0, null=True)),
                ('equip_cena', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_delka_kroku_procenta', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_BMR_procenta', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_zatez_procenta', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_income_flat', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_income_procenta', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_kapacita_flet', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_kapacita_procenta', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_XP_flat', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_XP_procenta', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_spanek_flat', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_spanek_procenta', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_cena_procenta', models.FloatField(blank=True, default=0)),
                ('equip_batoh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equip_batoh', to='adminapp.vybava')),
                ('equip_boty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equip_boty', to='adminapp.vybava')),
                ('equip_doplnek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equip_doplnek', to='adminapp.vybava')),
                ('equip_kalhoty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equip_kalhoty', to='adminapp.vybava')),
                ('equip_karimatka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equip_karimatka', to='adminapp.vybava')),
                ('equip_ponozky', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equip_ponozky', to='adminapp.vybava')),
                ('equip_spacak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equip_spacak', to='adminapp.vybava')),
                ('equip_triko', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equip_triko', to='adminapp.vybava')),
            ],
            options={
                'verbose_name': 'Co má Pepa na sobě',
                'verbose_name_plural': 'Co má Pepa na sobě',
            },
        ),
        migrations.CreateModel(
            name='InventarPolozkaVybava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnozstvi', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('polozka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.vybava')),
                ('inventar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vybaveni', to='pepaapp.pepa_inv')),
            ],
        ),
        migrations.CreateModel(
            name='InventarPolozkaFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnozstvi', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('polozka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.food_drink')),
                ('inventar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potraviny', to='pepaapp.pepa_inv')),
            ],
        ),
        migrations.CreateModel(
            name='pepa_snedl_polozka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('den', models.IntegerField(blank=True, default=1)),
                ('mnozstvi', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('snedeno_kcal', models.FloatField(blank=True, default=0)),
                ('snedeno_sytost', models.FloatField(blank=True, default=0)),
                ('snedeno_hydratace', models.FloatField(blank=True, default=0)),
                ('snedeno_hmotnost', models.FloatField(blank=True, default=0)),
                ('jidlo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.food_drink')),
                ('pepa_snedl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polozky', to='pepaapp.pepa_snedl')),
            ],
        ),
    ]
