# Generated by Django 5.1.5 on 2025-05-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pepa_snedl',
            name='snedeno_energie',
            field=models.FloatField(blank=True, default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='pepa_snedl_polozka',
            name='snedeno_energie',
            field=models.FloatField(blank=True, default=0, max_length=1000),
        ),
    ]
