# Generated by Django 5.1.5 on 2025-05-29 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pepaapp', '0002_pepa_snedl_snedeno_energie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hracipepa',
            name='kroky_BONUS',
        ),
    ]
