# Generated by Django 5.1.5 on 2025-05-30 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pepaapp', '0003_remove_hracipepa_kroky_bonus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hracipepa',
        ),
    ]
