# Generated by Django 5.1.5 on 2025-06-17 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_remove_pamet_pepa_zustatek_na_ucte'),
        ('pepaapp', '0004_delete_hracipepa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarpolozkafood',
            name='polozka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pepa_inventar_food', to='adminapp.food_drink'),
        ),
        migrations.AlterField(
            model_name='inventarpolozkavybava',
            name='polozka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pepa_inventar_vybava', to='adminapp.vybava'),
        ),
        migrations.AlterField(
            model_name='pepa_equip',
            name='equip_batoh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pepa_equip_batoh', to='adminapp.vybava'),
        ),
        migrations.AlterField(
            model_name='pepa_equip',
            name='equip_boty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pepa_equip_boty', to='adminapp.vybava'),
        ),
        migrations.AlterField(
            model_name='pepa_equip',
            name='equip_doplnek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pepa_equip_doplnek', to='adminapp.vybava'),
        ),
        migrations.AlterField(
            model_name='pepa_equip',
            name='equip_kalhoty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pepa_equip_kalhoty', to='adminapp.vybava'),
        ),
        migrations.AlterField(
            model_name='pepa_equip',
            name='equip_karimatka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pepa_equip_karimatka', to='adminapp.vybava'),
        ),
        migrations.AlterField(
            model_name='pepa_equip',
            name='equip_ponozky',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pepa_equip_ponozky', to='adminapp.vybava'),
        ),
        migrations.AlterField(
            model_name='pepa_equip',
            name='equip_spacak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pepa_equip_spacak', to='adminapp.vybava'),
        ),
        migrations.AlterField(
            model_name='pepa_equip',
            name='equip_triko',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pepa_equip_triko', to='adminapp.vybava'),
        ),
        migrations.AlterField(
            model_name='pepa_snedl_polozka',
            name='jidlo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pepa_snedl_polozka', to='adminapp.food_drink'),
        ),
    ]
