# Generated by Django 5.1.5 on 2025-07-18 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pepaapp', '0005_alter_inventarpolozkafood_polozka_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pepa_equip',
            name='equip_pozn',
        ),
    ]
