# Generated by Django 5.1.5 on 2025-05-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_drink',
            name='food_energie',
            field=models.FloatField(blank=True, default=0, max_length=1000),
        ),
    ]
