# Generated by Django 5.1.5 on 2025-05-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_food_drink_food_energie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hubnuti',
        ),
    ]
