# Generated by Django 5.1.5 on 2025-05-29 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_delete_hubnuti'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aktivita_kcal2',
            options={'verbose_name': 'ÝPOČET kcal/h', 'verbose_name_plural': 'ÝPOČET kcal/h'},
        ),
    ]
