# Generated by Django 5.1.5 on 2025-05-31 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_aktivita_kcal2_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pamet_pepa',
            name='pozn',
        ),
    ]
