# Generated by Django 5.1.5 on 2025-06-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_remove_pamet_pepa_pozn'),
    ]

    operations = [
        migrations.AddField(
            model_name='spanek',
            name='pozn',
            field=models.IntegerField(default=1),
        ),
    ]
