# Generated by Django 5.1.5 on 2025-06-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_spanek_pozn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pamet_pepa',
            name='zustatek_na_ucte',
        ),
    ]
