# Generated by Django 5.1.5 on 2025-06-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_remove_pamet_pepa_zustatek_na_ucte'),
    ]

    operations = [
        migrations.CreateModel(
            name='pamet_brunhilda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('den', models.IntegerField(blank=True)),
                ('energie', models.IntegerField(blank=True)),
                ('kondice', models.IntegerField(blank=True)),
                ('hydratace', models.IntegerField(blank=True)),
                ('sytost', models.IntegerField(blank=True)),
                ('volna_kapacita', models.FloatField(blank=True)),
                ('zatez', models.IntegerField(blank=True)),
                ('pepova_aktualni_vaha', models.FloatField(blank=True, default=0)),
                ('km_s_bonusem', models.FloatField(blank=True, default=0)),
                ('aktual_XP', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Paměť - BRUNHILDA',
                'verbose_name_plural': 'Paměť - BRUNHILDA',
            },
        ),
        migrations.CreateModel(
            name='pamet_karel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('den', models.IntegerField(blank=True)),
                ('energie', models.IntegerField(blank=True)),
                ('kondice', models.IntegerField(blank=True)),
                ('hydratace', models.IntegerField(blank=True)),
                ('sytost', models.IntegerField(blank=True)),
                ('volna_kapacita', models.FloatField(blank=True)),
                ('zatez', models.IntegerField(blank=True)),
                ('pepova_aktualni_vaha', models.FloatField(blank=True, default=0)),
                ('km_s_bonusem', models.FloatField(blank=True, default=0)),
                ('aktual_XP', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Paměť - KAREL',
                'verbose_name_plural': 'Paměť - KAREL',
            },
        ),
    ]
