# Generated by Django 5.1.5 on 2025-06-17 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_pamet_brunhilda_pamet_karel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pamet_brunhilda',
            old_name='pepova_aktualni_vaha',
            new_name='brunhilda_aktualni_vaha',
        ),
        migrations.RenameField(
            model_name='pamet_karel',
            old_name='pepova_aktualni_vaha',
            new_name='karlova_aktualni_vaha',
        ),
    ]
