# Generated by Django 5.1.5 on 2025-06-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_rename_pepova_aktualni_vaha_pamet_brunhilda_brunhilda_aktualni_vaha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pamet_brunhilda',
            name='pozn',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
