# Generated by Django 5.1.5 on 2025-06-18 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_pamet_brunhilda_pozn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pamet_brunhilda',
            name='pozn',
        ),
    ]
