# Generated by Django 5.1.5 on 2025-06-18 06:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0009_rename_pepova_aktualni_vaha_pamet_brunhilda_brunhilda_aktualni_vaha_and_more'),
        ('brunhildaapp', '0002_delete_brunhilda_zakladni_staty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='brunhilda_inv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('den', models.IntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('vaha_inventare', models.FloatField(default=1)),
                ('objem_inventare', models.FloatField(default=1)),
                ('cena_inv', models.FloatField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Brunhilda INV',
                'verbose_name_plural': 'Brunhilda INV',
            },
        ),
        migrations.CreateModel(
            name='brunhilda_snedl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('den', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('snedeno_kcal', models.FloatField(blank=True, default=0)),
                ('snedeno_sytost', models.FloatField(blank=True, default=0)),
                ('snedeno_hydratace', models.FloatField(blank=True, default=0)),
                ('snedeno_hmotnost', models.FloatField(blank=True, default=0)),
                ('snedeno_energie', models.FloatField(blank=True, default=0, max_length=1000)),
            ],
            options={
                'verbose_name': 'Co Brunhilda snědl',
                'verbose_name_plural': 'Co Brunhilda snědl',
            },
        ),
        migrations.CreateModel(
            name='brunhilda_zakladni_staty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=10)),
                ('vek', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('vyska', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('vaha', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('pohlavi', models.CharField(max_length=10)),
                ('delkakroku', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'BRUNHILDA - Základní staty',
                'verbose_name_plural': 'BRUNHILDA - Základní staty',
            },
        ),
        migrations.CreateModel(
            name='brunhilda_equip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('den', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('equip_pozn', models.CharField(blank=True, max_length=1000, null=True)),
                ('equip_zatez', models.FloatField(blank=True, default=0, null=True)),
                ('equip_objem', models.FloatField(blank=True, default=0, null=True)),
                ('equip_cena', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_delka_kroku_procenta', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_BMR_procenta', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_zatez_procenta', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_income_flat', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_income_procenta', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_kapacita_flet', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_kapacita_procenta', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_XP_flat', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_XP_procenta', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_spanek_flat', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_spanek_procenta', models.FloatField(blank=True, default=0)),
                ('equip_BONUS_cena_procenta', models.FloatField(blank=True, default=0)),
                ('equip_batoh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brunhilda_equip_batoh', to='adminapp.vybava')),
                ('equip_boty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brunhilda_equip_boty', to='adminapp.vybava')),
                ('equip_doplnek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brunhilda_equip_doplnek', to='adminapp.vybava')),
                ('equip_kalhoty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brunhilda_equip_kalhoty', to='adminapp.vybava')),
                ('equip_karimatka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brunhilda_equip_karimatka', to='adminapp.vybava')),
                ('equip_ponozky', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brunhilda_equip_ponozky', to='adminapp.vybava')),
                ('equip_spacak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brunhilda_equip_spacak', to='adminapp.vybava')),
                ('equip_triko', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brunhilda_equip_triko', to='adminapp.vybava')),
            ],
            options={
                'verbose_name': 'Co má Brunhilda na sobě',
                'verbose_name_plural': 'Co má Brunhilda na sobě',
            },
        ),
        migrations.CreateModel(
            name='brunhilda_snedl_polozka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('den', models.IntegerField(blank=True, default=1)),
                ('mnozstvi', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('snedeno_kcal', models.FloatField(blank=True, default=0)),
                ('snedeno_sytost', models.FloatField(blank=True, default=0)),
                ('snedeno_hydratace', models.FloatField(blank=True, default=0)),
                ('snedeno_hmotnost', models.FloatField(blank=True, default=0)),
                ('snedeno_energie', models.FloatField(blank=True, default=0, max_length=1000)),
                ('brunhilda_snedl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polozky', to='brunhildaapp.brunhilda_snedl')),
                ('jidlo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brunhilda_snedl_polozka', to='adminapp.food_drink')),
            ],
        ),
        migrations.CreateModel(
            name='InventarPolozkaFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnozstvi', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('inventar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potraviny', to='brunhildaapp.brunhilda_inv')),
                ('polozka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brunhilda_inventar_food', to='adminapp.food_drink')),
            ],
        ),
        migrations.CreateModel(
            name='InventarPolozkaVybava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnozstvi', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('inventar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vybaveni', to='brunhildaapp.brunhilda_inv')),
                ('polozka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brunhilda_inventar_vybava', to='adminapp.vybava')),
            ],
        ),
    ]
